# Generated by Django 2.2.3 on 2019-07-09 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.PositiveSmallIntegerField(choices=[(1, 'CRISPRpred'), (2, 'CRISPRpred++'), (3, 'CRISPRpred(SEQ)')])),
                ('model_name', models.CharField(max_length=100)),
                ('training_file', models.FileField(upload_to=projects.models.get_upload_path)),
                ('consent_for_file', models.BooleanField(verbose_name='Can we use the file for research purposes?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
